package sources.remotesource

/**
 * PROJECT : weather
 * DATE    : Fri 02/02/2024
 * TIME    : 22:18
 * USER    : mambo
 */

val VALID_RESPONSE_FORECAST = """
    {
  "location": {
    "name": "Nairobi",
    "region": "Nairobi Area",
    "country": "Kenya",
    "lat": -1.28,
    "lon": 36.82,
    "tz_id": "Africa/Nairobi",
    "localtime_epoch": 1706876430,
    "localtime": "2024-02-02 15:20"
  },
  "current": {
    "last_updated_epoch": 1706876100,
    "last_updated": "2024-02-02 15:15",
    "temp_c": 26,
    "temp_f": 78.8,
    "is_day": 1,
    "condition": {
      "text": "Partly cloudy",
      "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
      "code": 1003
    },
    "wind_mph": 11.9,
    "wind_kph": 19.1,
    "wind_degree": 80,
    "wind_dir": "E",
    "pressure_mb": 1023,
    "pressure_in": 30.21,
    "precip_mm": 0,
    "precip_in": 0,
    "humidity": 39,
    "cloud": 75,
    "feelslike_c": 25.4,
    "feelslike_f": 77.6,
    "vis_km": 10,
    "vis_miles": 6,
    "uv": 10,
    "gust_mph": 16.3,
    "gust_kph": 26.3
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2024-02-02",
        "date_epoch": 1706832000,
        "day": {
          "maxtemp_c": 26.4,
          "maxtemp_f": 79.5,
          "mintemp_c": 14.7,
          "mintemp_f": 58.5,
          "avgtemp_c": 19.9,
          "avgtemp_f": 67.8,
          "maxwind_mph": 11,
          "maxwind_kph": 17.6,
          "totalprecip_mm": 0.01,
          "totalprecip_in": 0,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 58,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 11
        },
        "astro": {
          "sunrise": "06:41 AM",
          "sunset": "06:51 PM",
          "moonrise": "No moonrise",
          "moonset": "11:59 AM",
          "moon_phase": "Last Quarter",
          "moon_illumination": 59,
          "is_moon_up": 1,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1706821200,
            "time": "2024-02-02 00:00",
            "temp_c": 16.8,
            "temp_f": 62.2,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.9,
            "wind_kph": 11.2,
            "wind_degree": 46,
            "wind_dir": "NE",
            "pressure_mb": 1019,
            "pressure_in": 30.08,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 72,
            "cloud": 15,
            "feelslike_c": 16.8,
            "feelslike_f": 62.2,
            "windchill_c": 16.8,
            "windchill_f": 62.2,
            "heatindex_c": 16.8,
            "heatindex_f": 62.2,
            "dewpoint_c": 11.7,
            "dewpoint_f": 53,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.3,
            "gust_kph": 18.2,
            "uv": 1,
            "short_rad": 0,
            "diff_rad": 0
          },
          {
            "time_epoch": 1706824800,
            "time": "2024-02-02 01:00",
            "temp_c": 16.5,
            "temp_f": 61.8,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 37,
            "wind_dir": "NE",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 72,
            "cloud": 13,
            "feelslike_c": 16.6,
            "feelslike_f": 61.8,
            "windchill_c": 16.6,
            "windchill_f": 61.8,
            "heatindex_c": 16.6,
            "heatindex_f": 61.8,
            "dewpoint_c": 11.6,
            "dewpoint_f": 52.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.8,
            "gust_kph": 17.4,
            "uv": 1,
            "short_rad": 0,
            "diff_rad": 0
          },
          {
            "time_epoch": 1706828400,
            "time": "2024-02-02 02:00",
            "temp_c": 16.2,
            "temp_f": 61.2,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 32,
            "wind_dir": "NNE",
            "pressure_mb": 1017,
            "pressure_in": 30.04,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 73,
            "cloud": 14,
            "feelslike_c": 16.2,
            "feelslike_f": 61.2,
            "windchill_c": 16.2,
            "windchill_f": 61.2,
            "heatindex_c": 16.2,
            "heatindex_f": 61.2,
            "dewpoint_c": 11.4,
            "dewpoint_f": 52.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10,
            "gust_kph": 16.1,
            "uv": 1,
            "short_rad": 0,
            "diff_rad": 0
          },
          {
            "time_epoch": 1706832000,
            "time": "2024-02-02 03:00",
            "temp_c": 15.8,
            "temp_f": 60.5,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 35,
            "wind_dir": "NE",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 73,
            "cloud": 12,
            "feelslike_c": 15.9,
            "feelslike_f": 60.5,
            "windchill_c": 15.9,
            "windchill_f": 60.5,
            "heatindex_c": 15.9,
            "heatindex_f": 60.5,
            "dewpoint_c": 11.1,
            "dewpoint_f": 52,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.3,
            "gust_kph": 13.4,
            "uv": 1,
            "short_rad": 0,
            "diff_rad": 0
          },
          {
            "time_epoch": 1706835600,
            "time": "2024-02-02 04:00",
            "temp_c": 15.3,
            "temp_f": 59.6,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.8,
            "wind_kph": 6.1,
            "wind_degree": 33,
            "wind_dir": "NNE",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 75,
            "cloud": 9,
            "feelslike_c": 15.3,
            "feelslike_f": 59.6,
            "windchill_c": 15.3,
            "windchill_f": 59.6,
            "heatindex_c": 15.3,
            "heatindex_f": 59.6,
            "dewpoint_c": 10.9,
            "dewpoint_f": 51.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7,
            "gust_kph": 11.3,
            "uv": 1,
            "short_rad": 0,
            "diff_rad": 0
          },
          {
            "time_epoch": 1706839200,
            "time": "2024-02-02 05:00",
            "temp_c": 15,
            "temp_f": 58.9,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 20,
            "wind_dir": "NNE",
            "pressure_mb": 1017,
            "pressure_in": 30.04,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 75,
            "cloud": 9,
            "feelslike_c": 15.4,
            "feelslike_f": 59.7,
            "windchill_c": 15.4,
            "windchill_f": 59.7,
            "heatindex_c": 15,
            "heatindex_f": 58.9,
            "dewpoint_c": 10.7,
            "dewpoint_f": 51.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.9,
            "gust_kph": 9.5,
            "uv": 1,
            "short_rad": 0,
            "diff_rad": 0
          },
          {
            "time_epoch": 1706842800,
            "time": "2024-02-02 06:00",
            "temp_c": 14.7,
            "temp_f": 58.5,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 3.1,
            "wind_kph": 5,
            "wind_degree": 17,
            "wind_dir": "NNE",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 77,
            "cloud": 10,
            "feelslike_c": 15.1,
            "feelslike_f": 59.1,
            "windchill_c": 15.1,
            "windchill_f": 59.1,
            "heatindex_c": 14.7,
            "heatindex_f": 58.5,
            "dewpoint_c": 10.6,
            "dewpoint_f": 51.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6,
            "gust_kph": 9.7,
            "uv": 1,
            "short_rad": 0,
            "diff_rad": 0
          },
          {
            "time_epoch": 1706846400,
            "time": "2024-02-02 07:00",
            "temp_c": 14.7,
            "temp_f": 58.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 3.4,
            "wind_kph": 5.4,
            "wind_degree": 11,
            "wind_dir": "NNE",
            "pressure_mb": 1019,
            "pressure_in": 30.08,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 78,
            "cloud": 11,
            "feelslike_c": 15,
            "feelslike_f": 59,
            "windchill_c": 15,
            "windchill_f": 59,
            "heatindex_c": 14.7,
            "heatindex_f": 58.5,
            "dewpoint_c": 10.9,
            "dewpoint_f": 51.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.3,
            "gust_kph": 10.2,
            "uv": 7,
            "short_rad": 0.86,
            "diff_rad": 0.4
          },
          {
            "time_epoch": 1706850000,
            "time": "2024-02-02 08:00",
            "temp_c": 17.1,
            "temp_f": 62.8,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 34,
            "wind_dir": "NE",
            "pressure_mb": 1019,
            "pressure_in": 30.09,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 69,
            "cloud": 11,
            "feelslike_c": 17.1,
            "feelslike_f": 62.8,
            "windchill_c": 17.1,
            "windchill_f": 62.8,
            "heatindex_c": 17.1,
            "heatindex_f": 62.8,
            "dewpoint_c": 11.4,
            "dewpoint_f": 52.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.8,
            "gust_kph": 9.4,
            "uv": 8,
            "short_rad": 29.78,
            "diff_rad": 9.54
          },
          {
            "time_epoch": 1706853600,
            "time": "2024-02-02 09:00",
            "temp_c": 19.4,
            "temp_f": 67,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6.5,
            "wind_kph": 10.4,
            "wind_degree": 48,
            "wind_dir": "NE",
            "pressure_mb": 1019,
            "pressure_in": 30.09,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 60,
            "cloud": 10,
            "feelslike_c": 19.4,
            "feelslike_f": 67,
            "windchill_c": 19.4,
            "windchill_f": 67,
            "heatindex_c": 19.4,
            "heatindex_f": 67,
            "dewpoint_c": 11.5,
            "dewpoint_f": 52.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7.5,
            "gust_kph": 12,
            "uv": 8,
            "short_rad": 94.04,
            "diff_rad": 19.59
          },
          {
            "time_epoch": 1706857200,
            "time": "2024-02-02 10:00",
            "temp_c": 21.2,
            "temp_f": 70.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 52,
            "wind_dir": "NE",
            "pressure_mb": 1018,
            "pressure_in": 30.07,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 53,
            "cloud": 7,
            "feelslike_c": 21.2,
            "feelslike_f": 70.2,
            "windchill_c": 21.2,
            "windchill_f": 70.2,
            "heatindex_c": 24.4,
            "heatindex_f": 75.9,
            "dewpoint_c": 11.3,
            "dewpoint_f": 52.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.7,
            "gust_kph": 14.1,
            "uv": 9,
            "short_rad": 637.68,
            "diff_rad": 154.34
          },
          {
            "time_epoch": 1706860800,
            "time": "2024-02-02 11:00",
            "temp_c": 23,
            "temp_f": 73.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 54,
            "wind_dir": "NE",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 46,
            "cloud": 4,
            "feelslike_c": 24.6,
            "feelslike_f": 76.3,
            "windchill_c": 23,
            "windchill_f": 73.4,
            "heatindex_c": 24.6,
            "heatindex_f": 76.3,
            "dewpoint_c": 10.8,
            "dewpoint_f": 51.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.3,
            "gust_kph": 14.9,
            "uv": 9,
            "short_rad": 746.22,
            "diff_rad": 150.24
          },
          {
            "time_epoch": 1706864400,
            "time": "2024-02-02 12:00",
            "temp_c": 24.4,
            "temp_f": 75.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 60,
            "wind_dir": "ENE",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 41,
            "cloud": 6,
            "feelslike_c": 25,
            "feelslike_f": 77.1,
            "windchill_c": 24.4,
            "windchill_f": 75.9,
            "heatindex_c": 25,
            "heatindex_f": 77.1,
            "dewpoint_c": 10.2,
            "dewpoint_f": 50.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.8,
            "gust_kph": 15.7,
            "uv": 9,
            "short_rad": 825.12,
            "diff_rad": 165.38
          },
          {
            "time_epoch": 1706868000,
            "time": "2024-02-02 13:00",
            "temp_c": 25.5,
            "temp_f": 77.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 66,
            "wind_dir": "ENE",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 35,
            "cloud": 7,
            "feelslike_c": 25.4,
            "feelslike_f": 77.7,
            "windchill_c": 25.5,
            "windchill_f": 77.9,
            "heatindex_c": 25.4,
            "heatindex_f": 77.7,
            "dewpoint_c": 9,
            "dewpoint_f": 48.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.8,
            "gust_kph": 17.4,
            "uv": 10,
            "short_rad": 871.9,
            "diff_rad": 194.62
          },
          {
            "time_epoch": 1706871600,
            "time": "2024-02-02 14:00",
            "temp_c": 26.3,
            "temp_f": 79.3,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 68,
            "wind_dir": "ENE",
            "pressure_mb": 1013,
            "pressure_in": 29.91,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 31,
            "cloud": 5,
            "feelslike_c": 25.6,
            "feelslike_f": 78.1,
            "windchill_c": 26.3,
            "windchill_f": 79.3,
            "heatindex_c": 25.6,
            "heatindex_f": 78.1,
            "dewpoint_c": 7.7,
            "dewpoint_f": 45.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.1,
            "gust_kph": 17.8,
            "uv": 10,
            "short_rad": 902.7,
            "diff_rad": 199.42
          },
          {
            "time_epoch": 1706875200,
            "time": "2024-02-02 15:00",
            "temp_c": 26,
            "temp_f": 78.8,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 11.9,
            "wind_kph": 19.1,
            "wind_degree": 80,
            "wind_dir": "E",
            "pressure_mb": 1023,
            "pressure_in": 30.21,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 39,
            "cloud": 75,
            "feelslike_c": 25.7,
            "feelslike_f": 78.2,
            "windchill_c": 26.4,
            "windchill_f": 79.5,
            "heatindex_c": 25.7,
            "heatindex_f": 78.2,
            "dewpoint_c": 7.4,
            "dewpoint_f": 45.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.3,
            "gust_kph": 26.3,
            "uv": 10,
            "short_rad": 910.37,
            "diff_rad": 187.02
          },
          {
            "time_epoch": 1706878800,
            "time": "2024-02-02 16:00",
            "temp_c": 26,
            "temp_f": 78.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 70,
            "wind_dir": "ENE",
            "pressure_mb": 1011,
            "pressure_in": 29.86,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 31,
            "cloud": 5,
            "feelslike_c": 25.4,
            "feelslike_f": 77.7,
            "windchill_c": 26,
            "windchill_f": 78.7,
            "heatindex_c": 25.4,
            "heatindex_f": 77.7,
            "dewpoint_c": 7.5,
            "dewpoint_f": 45.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.3,
            "gust_kph": 19.9,
            "uv": 10,
            "short_rad": 754.06,
            "diff_rad": 167.64
          },
          {
            "time_epoch": 1706882400,
            "time": "2024-02-02 17:00",
            "temp_c": 25,
            "temp_f": 77,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 11,
            "wind_kph": 17.6,
            "wind_degree": 71,
            "wind_dir": "ENE",
            "pressure_mb": 1011,
            "pressure_in": 29.86,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 34,
            "cloud": 6,
            "feelslike_c": 25,
            "feelslike_f": 77,
            "windchill_c": 25,
            "windchill_f": 77,
            "heatindex_c": 25,
            "heatindex_f": 77,
            "dewpoint_c": 8,
            "dewpoint_f": 46.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.6,
            "gust_kph": 20.3,
            "uv": 10,
            "short_rad": 636.8,
            "diff_rad": 155
          },
          {
            "time_epoch": 1706886000,
            "time": "2024-02-02 18:00",
            "temp_c": 23.1,
            "temp_f": 73.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 10.1,
            "wind_kph": 16.2,
            "wind_degree": 71,
            "wind_dir": "ENE",
            "pressure_mb": 1012,
            "pressure_in": 29.88,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 42,
            "cloud": 9,
            "feelslike_c": 24.5,
            "feelslike_f": 76.1,
            "windchill_c": 23.1,
            "windchill_f": 73.7,
            "heatindex_c": 24.5,
            "heatindex_f": 76.1,
            "dewpoint_c": 9.6,
            "dewpoint_f": 49.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.8,
            "gust_kph": 22.2,
            "uv": 9,
            "short_rad": 505.06,
            "diff_rad": 139.11
          },
          {
            "time_epoch": 1706889600,
            "time": "2024-02-02 19:00",
            "temp_c": 20.7,
            "temp_f": 69.3,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 68,
            "wind_dir": "ENE",
            "pressure_mb": 1013,
            "pressure_in": 29.92,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 51,
            "cloud": 11,
            "feelslike_c": 20.7,
            "feelslike_f": 69.3,
            "windchill_c": 20.7,
            "windchill_f": 69.3,
            "heatindex_c": 20.7,
            "heatindex_f": 69.3,
            "dewpoint_c": 10.3,
            "dewpoint_f": 50.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.7,
            "gust_kph": 23.7,
            "uv": 1,
            "short_rad": 388.66,
            "diff_rad": 109.22
          },
          {
            "time_epoch": 1706893200,
            "time": "2024-02-02 20:00",
            "temp_c": 19.6,
            "temp_f": 67.3,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 78,
            "wind_dir": "ENE",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 60,
            "cloud": 9,
            "feelslike_c": 19.6,
            "feelslike_f": 67.3,
            "windchill_c": 19.6,
            "windchill_f": 67.3,
            "heatindex_c": 19.6,
            "heatindex_f": 67.3,
            "dewpoint_c": 11.7,
            "dewpoint_f": 53.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.1,
            "gust_kph": 24.3,
            "uv": 1,
            "short_rad": 310.94,
            "diff_rad": 87.38
          },
          {
            "time_epoch": 1706896800,
            "time": "2024-02-02 21:00",
            "temp_c": 18.6,
            "temp_f": 65.5,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 78,
            "wind_dir": "ENE",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 70,
            "cloud": 10,
            "feelslike_c": 18.6,
            "feelslike_f": 65.5,
            "windchill_c": 18.6,
            "windchill_f": 65.5,
            "heatindex_c": 18.6,
            "heatindex_f": 65.5,
            "dewpoint_c": 13,
            "dewpoint_f": 55.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.3,
            "gust_kph": 23,
            "uv": 1,
            "short_rad": 259.12,
            "diff_rad": 72.82
          },
          {
            "time_epoch": 1706900400,
            "time": "2024-02-02 22:00",
            "temp_c": 18,
            "temp_f": 64.5,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 65,
            "wind_dir": "ENE",
            "pressure_mb": 1017,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 74,
            "cloud": 16,
            "feelslike_c": 18.1,
            "feelslike_f": 64.5,
            "windchill_c": 18.1,
            "windchill_f": 64.5,
            "heatindex_c": 18.1,
            "heatindex_f": 64.5,
            "dewpoint_c": 13.4,
            "dewpoint_f": 56,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.4,
            "gust_kph": 20,
            "uv": 1,
            "short_rad": 0,
            "diff_rad": 0
          },
          {
            "time_epoch": 1706904000,
            "time": "2024-02-02 23:00",
            "temp_c": 17.7,
            "temp_f": 63.9,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 56,
            "wind_dir": "ENE",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 76,
            "cloud": 18,
            "feelslike_c": 17.7,
            "feelslike_f": 63.9,
            "windchill_c": 17.7,
            "windchill_f": 63.9,
            "heatindex_c": 17.7,
            "heatindex_f": 63.9,
            "dewpoint_c": 13.4,
            "dewpoint_f": 56.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.1,
            "gust_kph": 17.9,
            "uv": 1,
            "short_rad": 0,
            "diff_rad": 0
          }
        ]
      }
     ]
    }
  }
""".trimIndent()

val INVALID_RESPONSE_FORECAST = """
{
  "location": {
    "name": "Nairobi",
    "region": "Nairobi Area",
    "country": "Kenya",
    "lat": -1.28,
    "lon": 36.82,
    "tz_id": "Africa/Nairobi",

    "feelslike_c": 25.4,
    "feelslike_f": 77.6,
    "vis_km": 10,
    "vis_miles": 6,
    "uv": 10,
    "gust_mph": 16.3,
    "gust_kph": 26.3
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2024-02-02",
        "date_epoch": 1706832000,
        "day": {
          "maxtemp_c": 26.4,
          "maxtemp_f": 79.5,
          "mintemp_c": 14.7,
          "mintemp_f": 58.5,
          "avgtemp_c": 19.9,
          "avgtemp_f": 67.8,
          "maxwind_mph": 11,
          "maxwind_kph": 17.6,
          "totalprecip_mm": 0.01,
          "totalprecip_in": 0,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 58,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 0,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000
          },
          "uv": 11
        },
        "astro": {
          "sunrise": "06:41 AM",
          "sunset": "06:51 PM",
          "moonrise": "No moonrise",
          "moonset": "11:59 AM",
          "moon_phase": "Last Quarter",
          "moon_illumination": 59,
          "is_moon_up": 1,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1706821200,
            "time": "2024-02-02 00:00",
            "temp_c": 16.8,
            
""".trimIndent()

val VALID_HISTORY_RESPONSE = """
    {
  "location": {
    "name": "Nairobi",
    "region": "Nairobi Area",
    "country": "Kenya",
    "lat": -1.28,
    "lon": 36.82,
    "tz_id": "Africa/Nairobi",
    "localtime_epoch": 1707072235,
    "localtime": "2024-02-04 21:43"
  },
  "forecast": {
    "forecastday": [
      {
        "date": "2024-02-04",
        "date_epoch": 1707004800,
        "day": {
          "maxtemp_c": 27.9,
          "maxtemp_f": 82.2,
          "mintemp_c": 15.5,
          "mintemp_f": 59.9,
          "avgtemp_c": 20.7,
          "avgtemp_f": 69.3,
          "maxwind_mph": 16.6,
          "maxwind_kph": 26.6,
          "totalprecip_mm": 0.06,
          "totalprecip_in": 0,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 64,
          "daily_will_it_rain": 0,
          "daily_chance_of_rain": 45,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
          },
          "uv": 10
        },
        "astro": {
          "sunrise": "06:41 AM",
          "sunset": "06:51 PM",
          "moonrise": "01:06 AM",
          "moonset": "01:36 PM",
          "moon_phase": "Waning Crescent",
          "moon_illumination": 40
        },
        "hour": [
          {
            "time_epoch": 1706994000,
            "time": "2024-02-04 00:00",
            "temp_c": 17.7,
            "temp_f": 63.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 50,
            "wind_dir": "NE",
            "pressure_mb": 1017,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 78,
            "cloud": 18,
            "feelslike_c": 17.7,
            "feelslike_f": 63.8,
            "windchill_c": 17.7,
            "windchill_f": 63.8,
            "heatindex_c": 17.7,
            "heatindex_f": 63.8,
            "dewpoint_c": 13.8,
            "dewpoint_f": 56.8,
            "will_it_rain": 0,
            "chance_of_rain": 45,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11,
            "gust_kph": 17.7,
            "uv": 1
          },
          {
            "time_epoch": 1706997600,
            "time": "2024-02-04 01:00",
            "temp_c": 17.2,
            "temp_f": 63,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.6,
            "wind_kph": 9,
            "wind_degree": 41,
            "wind_dir": "NE",
            "pressure_mb": 1016,
            "pressure_in": 30.01,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 80,
            "cloud": 14,
            "feelslike_c": 17.2,
            "feelslike_f": 63,
            "windchill_c": 17.2,
            "windchill_f": 63,
            "heatindex_c": 17.2,
            "heatindex_f": 63,
            "dewpoint_c": 13.7,
            "dewpoint_f": 56.7,
            "will_it_rain": 0,
            "chance_of_rain": 45,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10,
            "gust_kph": 16.1,
            "uv": 1
          },
          {
            "time_epoch": 1707001200,
            "time": "2024-02-04 02:00",
            "temp_c": 16.9,
            "temp_f": 62.4,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 41,
            "wind_dir": "NE",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 81,
            "cloud": 14,
            "feelslike_c": 16.9,
            "feelslike_f": 62.4,
            "windchill_c": 16.9,
            "windchill_f": 62.4,
            "heatindex_c": 16.9,
            "heatindex_f": 62.4,
            "dewpoint_c": 13.6,
            "dewpoint_f": 56.6,
            "will_it_rain": 0,
            "chance_of_rain": 45,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.6,
            "gust_kph": 17.1,
            "uv": 1
          },
          {
            "time_epoch": 1707004800,
            "time": "2024-02-04 03:00",
            "temp_c": 16.5,
            "temp_f": 61.7,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 35,
            "wind_dir": "NE",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 83,
            "cloud": 13,
            "feelslike_c": 16.5,
            "feelslike_f": 61.7,
            "windchill_c": 16.5,
            "windchill_f": 61.7,
            "heatindex_c": 16.5,
            "heatindex_f": 61.7,
            "dewpoint_c": 13.5,
            "dewpoint_f": 56.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.7,
            "gust_kph": 15.6,
            "uv": 1
          },
          {
            "time_epoch": 1707008400,
            "time": "2024-02-04 04:00",
            "temp_c": 16.1,
            "temp_f": 61,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 19,
            "wind_dir": "NNE",
            "pressure_mb": 1016,
            "pressure_in": 30,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 84,
            "cloud": 11,
            "feelslike_c": 16.1,
            "feelslike_f": 61,
            "windchill_c": 16.1,
            "windchill_f": 61,
            "heatindex_c": 16.1,
            "heatindex_f": 61,
            "dewpoint_c": 13.4,
            "dewpoint_f": 56.2,
            "will_it_rain": 0,
            "chance_of_rain": 45,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.1,
            "gust_kph": 14.7,
            "uv": 1
          },
          {
            "time_epoch": 1707012000,
            "time": "2024-02-04 05:00",
            "temp_c": 15.8,
            "temp_f": 60.5,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 24,
            "wind_dir": "NNE",
            "pressure_mb": 1016,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 85,
            "cloud": 12,
            "feelslike_c": 15.8,
            "feelslike_f": 60.5,
            "windchill_c": 15.8,
            "windchill_f": 60.5,
            "heatindex_c": 15.8,
            "heatindex_f": 60.5,
            "dewpoint_c": 13.3,
            "dewpoint_f": 55.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.4,
            "gust_kph": 13.5,
            "uv": 1
          },
          {
            "time_epoch": 1707015600,
            "time": "2024-02-04 06:00",
            "temp_c": 15.6,
            "temp_f": 60.1,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 40,
            "wind_dir": "NE",
            "pressure_mb": 1017,
            "pressure_in": 30.03,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 85,
            "cloud": 16,
            "feelslike_c": 15.6,
            "feelslike_f": 60.1,
            "windchill_c": 15.6,
            "windchill_f": 60.1,
            "heatindex_c": 15.6,
            "heatindex_f": 60.1,
            "dewpoint_c": 13.2,
            "dewpoint_f": 55.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.1,
            "gust_kph": 14.7,
            "uv": 1
          },
          {
            "time_epoch": 1707019200,
            "time": "2024-02-04 07:00",
            "temp_c": 15.5,
            "temp_f": 59.9,
            "is_day": 1,
            "condition": {
              "text": "Partly cloudy",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 5.1,
            "wind_kph": 8.3,
            "wind_degree": 45,
            "wind_dir": "NE",
            "pressure_mb": 1018,
            "pressure_in": 30.05,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 86,
            "cloud": 26,
            "feelslike_c": 15.5,
            "feelslike_f": 59.9,
            "windchill_c": 15.5,
            "windchill_f": 59.9,
            "heatindex_c": 15.5,
            "heatindex_f": 59.9,
            "dewpoint_c": 13.2,
            "dewpoint_f": 55.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.5,
            "gust_kph": 15.3,
            "uv": 8
          },
          {
            "time_epoch": 1707022800,
            "time": "2024-02-04 08:00",
            "temp_c": 17.7,
            "temp_f": 63.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 41,
            "wind_dir": "NE",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 77,
            "cloud": 20,
            "feelslike_c": 17.7,
            "feelslike_f": 63.9,
            "windchill_c": 17.7,
            "windchill_f": 63.9,
            "heatindex_c": 17.7,
            "heatindex_f": 63.9,
            "dewpoint_c": 13.6,
            "dewpoint_f": 56.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.5,
            "gust_kph": 13.6,
            "uv": 8
          },
          {
            "time_epoch": 1707026400,
            "time": "2024-02-04 09:00",
            "temp_c": 20.1,
            "temp_f": 68.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 9.6,
            "wind_kph": 15.5,
            "wind_degree": 47,
            "wind_dir": "NE",
            "pressure_mb": 1018,
            "pressure_in": 30.07,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 67,
            "cloud": 25,
            "feelslike_c": 20.1,
            "feelslike_f": 68.1,
            "windchill_c": 20.1,
            "windchill_f": 68.1,
            "heatindex_c": 20.1,
            "heatindex_f": 68.1,
            "dewpoint_c": 13.8,
            "dewpoint_f": 56.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.1,
            "gust_kph": 17.8,
            "uv": 9
          },
          {
            "time_epoch": 1707030000,
            "time": "2024-02-04 10:00",
            "temp_c": 22.1,
            "temp_f": 71.7,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 11,
            "wind_kph": 17.6,
            "wind_degree": 50,
            "wind_dir": "NE",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 59,
            "cloud": 15,
            "feelslike_c": 24.6,
            "feelslike_f": 76.2,
            "windchill_c": 22.1,
            "windchill_f": 71.7,
            "heatindex_c": 24.6,
            "heatindex_f": 76.2,
            "dewpoint_c": 13.7,
            "dewpoint_f": 56.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.6,
            "gust_kph": 20.3,
            "uv": 9
          },
          {
            "time_epoch": 1707033600,
            "time": "2024-02-04 11:00",
            "temp_c": 24,
            "temp_f": 75.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 11.9,
            "wind_kph": 19.1,
            "wind_degree": 53,
            "wind_dir": "NE",
            "pressure_mb": 1017,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 50,
            "cloud": 9,
            "feelslike_c": 25.2,
            "feelslike_f": 77.3,
            "windchill_c": 24,
            "windchill_f": 75.1,
            "heatindex_c": 25.2,
            "heatindex_f": 77.3,
            "dewpoint_c": 12.9,
            "dewpoint_f": 55.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.6,
            "gust_kph": 22,
            "uv": 9
          },
          {
            "time_epoch": 1707037200,
            "time": "2024-02-04 12:00",
            "temp_c": 25.5,
            "temp_f": 77.9,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 59,
            "wind_dir": "ENE",
            "pressure_mb": 1015,
            "pressure_in": 29.98,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 43,
            "cloud": 18,
            "feelslike_c": 25.9,
            "feelslike_f": 78.5,
            "windchill_c": 25.5,
            "windchill_f": 77.8,
            "heatindex_c": 25.9,
            "heatindex_f": 78.5,
            "dewpoint_c": 12.1,
            "dewpoint_f": 53.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.4,
            "gust_kph": 23.2,
            "uv": 10
          },
          {
            "time_epoch": 1707040800,
            "time": "2024-02-04 13:00",
            "temp_c": 26.7,
            "temp_f": 80,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 62,
            "wind_dir": "ENE",
            "pressure_mb": 1014,
            "pressure_in": 29.94,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 39,
            "cloud": 18,
            "feelslike_c": 26.5,
            "feelslike_f": 79.8,
            "windchill_c": 26.7,
            "windchill_f": 80,
            "heatindex_c": 26.5,
            "heatindex_f": 79.8,
            "dewpoint_c": 11.6,
            "dewpoint_f": 53,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.4,
            "gust_kph": 23.2,
            "uv": 10
          },
          {
            "time_epoch": 1707044400,
            "time": "2024-02-04 14:00",
            "temp_c": 27.4,
            "temp_f": 81.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.3,
            "wind_kph": 19.8,
            "wind_degree": 66,
            "wind_dir": "ENE",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 36,
            "cloud": 12,
            "feelslike_c": 26.9,
            "feelslike_f": 80.5,
            "windchill_c": 27.4,
            "windchill_f": 81.4,
            "heatindex_c": 26.9,
            "heatindex_f": 80.5,
            "dewpoint_c": 10.9,
            "dewpoint_f": 51.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.2,
            "gust_kph": 22.8,
            "uv": 10
          },
          {
            "time_epoch": 1707048000,
            "time": "2024-02-04 15:00",
            "temp_c": 27.9,
            "temp_f": 82.2,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 68,
            "wind_dir": "ENE",
            "pressure_mb": 1011,
            "pressure_in": 29.86,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 33,
            "cloud": 9,
            "feelslike_c": 27.1,
            "feelslike_f": 80.8,
            "windchill_c": 27.9,
            "windchill_f": 82.2,
            "heatindex_c": 27.1,
            "heatindex_f": 80.8,
            "dewpoint_c": 10.1,
            "dewpoint_f": 50.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.4,
            "gust_kph": 23.2,
            "uv": 10
          },
          {
            "time_epoch": 1707051600,
            "time": "2024-02-04 16:00",
            "temp_c": 27.8,
            "temp_f": 82,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 13.2,
            "wind_kph": 21.2,
            "wind_degree": 69,
            "wind_dir": "ENE",
            "pressure_mb": 1010,
            "pressure_in": 29.84,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 32,
            "cloud": 12,
            "feelslike_c": 26.9,
            "feelslike_f": 80.5,
            "windchill_c": 27.8,
            "windchill_f": 82,
            "heatindex_c": 26.9,
            "heatindex_f": 80.5,
            "dewpoint_c": 9.6,
            "dewpoint_f": 49.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.2,
            "gust_kph": 24.4,
            "uv": 10
          },
          {
            "time_epoch": 1707055200,
            "time": "2024-02-04 17:00",
            "temp_c": 26.9,
            "temp_f": 80.5,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 14.5,
            "wind_kph": 23.4,
            "wind_degree": 71,
            "wind_dir": "ENE",
            "pressure_mb": 1011,
            "pressure_in": 29.84,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 34,
            "cloud": 14,
            "feelslike_c": 26.4,
            "feelslike_f": 79.5,
            "windchill_c": 26.9,
            "windchill_f": 80.5,
            "heatindex_c": 26.4,
            "heatindex_f": 79.5,
            "dewpoint_c": 9.7,
            "dewpoint_f": 49.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.7,
            "gust_kph": 26.9,
            "uv": 10
          },
          {
            "time_epoch": 1707058800,
            "time": "2024-02-04 18:00",
            "temp_c": 24.5,
            "temp_f": 76.1,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 16.6,
            "wind_kph": 26.6,
            "wind_degree": 65,
            "wind_dir": "ENE",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 46,
            "cloud": 12,
            "feelslike_c": 25.3,
            "feelslike_f": 77.6,
            "windchill_c": 24.5,
            "windchill_f": 76.1,
            "heatindex_c": 25.3,
            "heatindex_f": 77.6,
            "dewpoint_c": 12.1,
            "dewpoint_f": 53.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 21.1,
            "gust_kph": 34,
            "uv": 9
          },
          {
            "time_epoch": 1707062400,
            "time": "2024-02-04 19:00",
            "temp_c": 21.3,
            "temp_f": 70.4,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 16.3,
            "wind_kph": 26.3,
            "wind_degree": 64,
            "wind_dir": "ENE",
            "pressure_mb": 1014,
            "pressure_in": 29.95,
            "precip_mm": 0.01,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 60,
            "cloud": 86,
            "feelslike_c": 21.3,
            "feelslike_f": 70.4,
            "windchill_c": 21.3,
            "windchill_f": 70.4,
            "heatindex_c": 24.5,
            "heatindex_f": 76,
            "dewpoint_c": 13.4,
            "dewpoint_f": 56.1,
            "will_it_rain": 0,
            "chance_of_rain": 45,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 23.2,
            "gust_kph": 37.3,
            "uv": 1
          },
          {
            "time_epoch": 1707066000,
            "time": "2024-02-04 20:00",
            "temp_c": 19.9,
            "temp_f": 67.7,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 13.6,
            "wind_kph": 22,
            "wind_degree": 65,
            "wind_dir": "ENE",
            "pressure_mb": 1016,
            "pressure_in": 29.99,
            "precip_mm": 0.01,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 69,
            "cloud": 81,
            "feelslike_c": 19.9,
            "feelslike_f": 67.7,
            "windchill_c": 19.9,
            "windchill_f": 67.7,
            "heatindex_c": 19.9,
            "heatindex_f": 67.7,
            "dewpoint_c": 13.9,
            "dewpoint_f": 57,
            "will_it_rain": 0,
            "chance_of_rain": 45,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 19.8,
            "gust_kph": 31.8,
            "uv": 1
          },
          {
            "time_epoch": 1707069600,
            "time": "2024-02-04 21:00",
            "temp_c": 18.8,
            "temp_f": 65.8,
            "is_day": 0,
            "condition": {
              "text": "Clear",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 11,
            "wind_kph": 17.6,
            "wind_degree": 62,
            "wind_dir": "ENE",
            "pressure_mb": 1017,
            "pressure_in": 30.02,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 75,
            "cloud": 18,
            "feelslike_c": 18.8,
            "feelslike_f": 65.8,
            "windchill_c": 18.8,
            "windchill_f": 65.8,
            "heatindex_c": 18.8,
            "heatindex_f": 65.8,
            "dewpoint_c": 14.3,
            "dewpoint_f": 57.7,
            "will_it_rain": 0,
            "chance_of_rain": 45,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 16.6,
            "gust_kph": 26.8,
            "uv": 1
          },
          {
            "time_epoch": 1707073200,
            "time": "2024-02-04 22:00",
            "temp_c": 17.9,
            "temp_f": 64.2,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 53,
            "wind_dir": "NE",
            "pressure_mb": 1018,
            "pressure_in": 30.05,
            "precip_mm": 0.01,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 81,
            "cloud": 73,
            "feelslike_c": 17.9,
            "feelslike_f": 64.3,
            "windchill_c": 17.9,
            "windchill_f": 64.3,
            "heatindex_c": 17.9,
            "heatindex_f": 64.3,
            "dewpoint_c": 14.6,
            "dewpoint_f": 58.3,
            "will_it_rain": 0,
            "chance_of_rain": 45,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.4,
            "gust_kph": 23.2,
            "uv": 1
          },
          {
            "time_epoch": 1707076800,
            "time": "2024-02-04 23:00",
            "temp_c": 17.3,
            "temp_f": 63.1,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain possible",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 46,
            "wind_dir": "NE",
            "pressure_mb": 1018,
            "pressure_in": 30.06,
            "precip_mm": 0.02,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 86,
            "cloud": 73,
            "feelslike_c": 17.3,
            "feelslike_f": 63.1,
            "windchill_c": 17.3,
            "windchill_f": 63.1,
            "heatindex_c": 17.3,
            "heatindex_f": 63.1,
            "dewpoint_c": 14.9,
            "dewpoint_f": 58.7,
            "will_it_rain": 0,
            "chance_of_rain": 45,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.3,
            "gust_kph": 19.7,
            "uv": 1
          }
        ]
      }
    ]
  }
}
""".trimIndent()
val INVALID_HISTORY_RESPONSE = """
    {
  "location": {
    "name": "Nairobi",
    "region": "Nairobi Area",
    "country": "Kenya",
    "lat": -1.28,
    "lon": 36.82,
    "tz_id": "Africa/Nairobi",
    "localtime_epoch": 1707072235,
    "localtime": "2024-02-04 21:43"
  },
    "forecastday
  }
}
""".trimIndent()
